name: Deploy to AWS with Terraform

on:
  push:
    branches:
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build project (TypeScript)
        run: npm run build

      - name: Install production dependencies only
        run: npm ci --production

      - name: Package Lambda function
        run: |
          cp -r node_modules dist/
          cp package.json dist/

          cd dist
          zip -r user-management.zip . -x "*.map"
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3

      - name: Terraform Init
        run: |
          rm -f .terraform.lock.hcl
          terraform init -upgrade
        working-directory: deploy/iac-qa

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: deploy/iac-qa
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate
        working-directory: deploy/iac-qa

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: deploy/iac-qa
        env:
          TF_VAR_sendgrid_api_key: ${{ secrets.TF_VAR_SENDGRID_API_KEY }}
          TF_VAR_sendgrid_from_email: ${{ secrets.TF_VAR_SENDGRID_FROM_EMAIL }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: deploy/iac-qa
        env:
          TF_VAR_sendgrid_api_key: ${{ secrets.TF_VAR_SENDGRID_API_KEY }}
          TF_VAR_sendgrid_from_email: ${{ secrets.TF_VAR_SENDGRID_FROM_EMAIL }}

      - name: Output API URL
        run: terraform output api_gateway_url
        working-directory: deploy/iac-qa
